Update Map 22.10
i-Vertix/i-vertix-documentation pull request #24
Opened 2024-03-22 15:58 UTC by robertog85

2024-04-22 06:44 UTC, joschi99 requested changes
Ciao Roberto,
direi che va bene, ma ci sono 2-3 file che hanno delle dimensioni troppo grandi e bisogna ridurli.

2024-04-22 06:44 UTC, joschi99 commented on monitoring_versioned_docs/version-22.10/assets/maps/create_marker_map.gif
Immagine troppo grande, da ridurre sotto 1MB

2024-04-22 06:44 UTC, joschi99 commented on monitoring_versioned_docs/version-22.10/assets/maps/service_status_on_host_icon.gif
Immagine troppo grande, da ridurre sotto 1MB

2024-04-22 12:55 UTC, robertog85 commented on monitoring_versioned_docs/version-22.10/assets/maps/create_marker_map.gif
ho sostituito le gif con due immagini

2024-04-22 12:55 UTC, robertog85 commented on monitoring_versioned_docs/version-22.10/assets/maps/service_status_on_host_icon.gif
ho sostituito le gif con due immagini

2024-05-10 03:43 UTC, joschi99 approved these changes

2024-05-10 03:44 UTC, joschi99 approved these changes

2024-05-10 03:44 UTC, merged