update images part 1
i-Vertix/i-vertix-documentation pull request #8
Opened 2023-10-03 08:44 UTC by robertog85

update some images with new version

2023-11-02 13:58 UTC, joschi99 requested changes
Ciao Roberto,

in gran parte mi sembra molto buono, ho messo qualche commento per modifiche

2023-11-02 13:58 UTC, joschi99 commented on monitoring_versioned_docs/version-22.10/i-vertix-e2e/e2e-configuration.md
> +You need to create a host manually, see the topic [how to create a host](../monitoring-resources/monitoring-hosts/create-host-manually.md).
non è richiesto per forza di creare un host dedicato per il E2E, si potrebbe anche legare ad un host esistente. Modifica che sia chiaro.
Inoltre non metterei la descizione di come creare un host, basta avere il link (doppione)

2023-11-02 13:58 UTC, joschi99 commented on monitoring_versioned_docs/version-22.10/i-vertix-e2e/e2e-configuration.md
> +Press the button + Add Scenario:
Aggiunge anche un screenshot per il dettaglio del scenario (ho un animated gif che sostituisce 2-3 immagini qui)

2023-11-02 13:58 UTC, joschi99 commented on monitoring_versioned_docs/version-22.10/i-vertix-e2e/e2e-configuration.md
> +
speiga che adesso si possono selezionare i singoli step del scenario e vedere le info

2023-11-02 13:58 UTC, joschi99 commented on monitoring_versioned_sidebars/22.10-sidebar.yaml
> +  - id: i-vertix-e2e
non mettere come menu principale, ma metterei sotto "monitoring ressources"

2023-11-03 09:10 UTC, robertog85 commented on monitoring_versioned_docs/version-22.10/i-vertix-e2e/e2e-configuration.md
> +You need to create a host manually, see the topic [how to create a host](../monitoring-resources/monitoring-hosts/create-host-manually.md).
Ok, fatto

2023-11-03 09:10 UTC, robertog85 commented on monitoring_versioned_docs/version-22.10/i-vertix-e2e/e2e-configuration.md
> +
Ok, fatto

2023-11-03 09:10 UTC, robertog85 commented on monitoring_versioned_sidebars/22.10-sidebar.yaml
> +  - id: i-vertix-e2e
Ok, fatto

2023-11-06 11:18 UTC, robertog85 commented on monitoring_versioned_docs/version-22.10/i-vertix-e2e/e2e-configuration.md
> +Press the button + Add Scenario:
fatto

2023-11-10 08:17 UTC, flex-pgum approved these changes

2023-11-10 08:53 UTC, joschi99 approved these changes

2023-11-10 11:22 UTC, merged